### ISSUE TITLE
Feature Request: Support for Moon  visualization

### ISSUE THREAD

**Issue by Danieldiazi** [AitorDB/home-assistant-sun-card#144]
Hi!
Fantastic card, very beautiful and useful!!
I wonder if in the future will be possible to adapt this card in order to show Moon information. There are integrations like Astroweather that provide Moon information, and it will be fantastic if it shows in a card like "home-assisstant-sun-card". I suppose it will be difficult, this card is named "sun-card" and I'm asking for Moon support :)

**Comment by modul8** [comment]
I would love to see this also!
Great card already though!

**Comment by Tom-ahawk** [comment]
Its possible to get moon data from ipgeolocation.io like:
```
  - platform: rest
    resource: https://api.ipgeolocation.io/astronomy?apiKey=MyKey&location=MyTown,MyCountry
    name: Moon API
    scan_interval: 1200
    json_attributes: 
      - date
      - current_time
      - moonrise
      - moonset
      - moon_status
      - moon_altitude
      - moon_distance
      - moon_azimuth
      - moon_parallactic_angle
    value_template: '{{value_json.moon_status}}'
```
```
date: 2022-11-24
current_time: 19:32:50.036
sunrise: 08:36
moonrise: 09:44
moonset: 15:09
moon_status: -
moon_altitude: -26.863470965430853
moon_distance: 364301.28898391494
moon_azimuth: 265.84440759063875
moon_parallactic_angle: 27.564141243389596
friendly_name: Moon API

```
Would be nice to see the Moon path in your card.
