### ISSUE TITLE
some configuration options not working

### ISSUE THREAD

**Issue by squirtbrnr** [AitorDB/home-assistant-sun-card#72]
I tried configuring the card and it seems like only some of the configuration options are working.  I wanted to use 24 hour time, and show the azimuth and elevation.  However, only the title and language options have any affect on the card when I refresh/clear cache.

My config is:
```
      - type: 'custom:sun-card'
        title: Sunrise & Sunset
        language: en
        fields:
          - azimuth: true
          - elevation: true
        use12hourClock: false
```

The title shows up and changes, the language changes if I use another language.  The times are still in 12 hour format and azimuth and elevation do not show.  I even tried the following config and there was no change to the display:
```
      - type: 'custom:sun-card'
        use12hourClock: false
```

There are no errors in the logs.

**Comment by wasyl00** [comment]
I have the same problem. Can't force 24 hour clock. My config is below but I force 24 hours clock in user profile in the latest release 2021.6.0

  **unit_system: metric
  time_zone: Europe/London**

  **use12hourClock: false**  <-does not work for me.

**Comment by AitorDB** [comment]
My bad, Github is showing the  develop branch instead the main one, I need to fix that, in the current version you need to use `timeFormat: '24h'`

**Comment by wasyl00** [comment]
Works now, thanks!

**Comment by AitorDB** [comment]
No problem! next version will change it but it will include a visual editor so it will be easier to set up

**Comment by squirtbrnr** [comment]
thanks, that fixed the 24h format.  However, my elevation and azimuth is still not showing up.

```
      - type: 'custom:sun-card'
        fields:
          - azimuth: true
          - elevation: true
        timeFormat: '24h'
```

<img width="383" alt="Screen Shot 2021-06-03 at 11 30 47 PM" src="https://user-images.githubusercontent.com/35356217/120745952-d10eb180-c4c3-11eb-8738-a899a6358927.png">
